services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=fundraising_school_db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d fundraising_school_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@db:5432/fundraising_school_db?sslmode=disable
      - PORT=8080
      - LINKEDIN_USER=pirajulian568@gmail.com
      - LINKEDIN_PASSWORD=Josepira1*
    depends_on:
      db:
        condition: service_healthy
