services:
  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ctw_dashboard
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_BUCKET=fundraising-school
      - AWS_ACCESS_KEY_ID=AKIAZQ3DRGAFREAOLE5B
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-1
      - DB_SOURCE=postgresql://root:secret@db:5432/ctw_dashboard
      - LINKEDIN_USER=fabian@makers.ngo
      - LINKEDIN_PASSWORD=M#Build#M
      - PORT=80
      - API_KEY=995597e6bd3d94ea47e2b1d8d5d6a62c6311a50f28ba05eae405d172698e1238
    depends_on:
      db:
        condition: service_healthy